apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: flask-ns
spec:
  replicas: 4
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: saiteja4751/flask-demo:latest
        ports:
        - containerPort: 5000